### PR TITLE
Update Packages-Root

### PR DESCRIPTION
**Pull request by omsenjalia**

### CODE REVIEW

**Comment by omsenjalia** [comment]
Oops

**Comment by boredland** [comment]
did you want me to rebase onto the current version of iso-profiles? good idea 🍡

**Comment by omsenjalia** [comment]
> did you want me to rebase onto the current version of iso-profiles? good idea 🍡

Wdym?

**Comment by boredland** [comment]
I was wondering what this PR could have been about, and thought that it perhaps was about getting our iso profile on top of the others and probably fetch some changes in the area of root packages. So I rebased and don't think there were notable changes for us.

**Comment by omsenjalia** [comment]
It was accidently opened while I was working this repo to make a stable iso, but I didn't managed to do that, could you please build a stable iso support

**Comment by boredland** [comment]
what do you mean with a "stable iso"?

**Comment by omsenjalia** [comment]
> what do you mean with a "stable iso"?

Low ram usage and less laggy

**Comment by boredland** [comment]
I (and I suppose a lot more people) use manjaro sway on a daily basis without it being laggy or sth.

this is my machine with a heavy vscode project open, two firefoxes, a chrome window with teams, slack open:

image

According to my system info, sway itself takes like 100Mb. Waybar we tried to streamline towards lower ram usage. So without further pointers I'd say whatever problem you face is a bug on your machine. Without further information that is really hard to do. In general: Manjaro has no such things as stable releases. "Stable" refers to the usage of the stable package repository. We offer images that point to the stable package repo. There is nothing more "stable" in a rolling release distro than that. If you download a Gnome ISO for example, it will update to the latest stable repo, as soon as you run pacman.

**Comment by boredland** [comment]
Just to rule that out: are you on a nvidia card?

**Comment by omsenjalia** [comment]
> Just to rule that out: are you on a nvidia card?

No, I am on 4GB laptop using Manjaro Cutefish

**Comment by boredland** [comment]
So.. this isn't about sway?

**Comment by omsenjalia** [comment]
> So.. this isn't about sway?

Nope

**Pull request closed without merging**
